disabled unused macro declaration that was causing conflict
disabled SPIFFS redeclaration that was creating declaration conflict as a byproduct in sources that would include JPEGDecoder.h
This was the cause of error:
JPEGDecoder.h:48:20: error: conflicting declaration 'fs::SPIFFSFS LittleFS'
whenever JPEGDecoder.h was included before inclusion of SPIFFS-related headers.